spring.application.name=tours

server.port=8082

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:tours_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

stakeholders.service.url=${STAKEHOLDERS_URL:http://localhost:8080}
blog.service.url=${BLOG_URL:http://localhost:8081}
nats.url=${NATS_URL:nats://localhost:4222}

stakeholders.grpc.host=${STAKEHOLDERS_GRPC_HOST:localhost}
stakeholders.grpc.port=${STAKEHOLDERS_GRPC_PORT:9090}

grpc.server.port=${GRPC_SERVER_PORT:9091}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

upload.dir=${UPLOAD_DIR:uploads}
